[package]
name = "nil_core"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
c-kzg = "2.1.5"
hex = "0.4.3"
num-bigint = "0.4.6"
num-integer = "0.1.46"
num-traits = "0.2.19"
rand = "0.9.2"
sha2 = "0.10.9"
thiserror = "2.0.17"
